; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Sun Aug 16 2020 17:43:09 GMT+0200 (Central European Summer Time)

